name: Lint Code

description: "Reusable workflow to run linting checks on the codebase."

on:
  workflow_call:
    inputs:
      lint-command:
        description: "Linting command to run"
        required: false
        default: "npm run lint"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"  # Default Node version; customize as needed

      # Install dependencies (if needed for linting)
      - name: Install dependencies
        run: npm ci

      # Run linting command
      - name: Run lint
        run: ${{ inputs.lint-command }}

      # Upload linting results (optional, requires ESLint configuration to output JSON)
      - name: Upload Linting Results
        if: success() && fileExists('lint-results.json')
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: lint-results.json
